---
abstract: 'METS parse class.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: METS-Parse-Simple
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  XML::Simple: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=METS-Parse-Simple
  homepage: https://github.com/tupinek/METS-Parse-Simple
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/METS-Parse-Simple
version: '0.01'
